### ISSUE TITLE
DocumenterLaTeX.jl stop working for me

### ISSUE THREAD

**Issue by DrKrar** [JuliaDocs/DocumenterLaTeX.jl#7]
I had already make a `PDF` document using this Package but without any reason  I now repeatedly get the error blow. The docker service where used in travis for julia 1.1 on linux
Repository : [GitHub.com](https://github.com/DrKrar/GeoEfficiency.jl/)
```
┌ Error: LaTeXWriter: failed to compile tex with docker. Logs and partial output can be found in /tmp/tmpgIHLi9.
│   exception =
│    failed process: Process(`docker exec -u zeptodoctor latex-container bash -c 'mkdir /home/zeptodoctor/build
│    cd /home/zeptodoctor/build
│    cp -r /mnt/. .
│    latexmk -f -interaction=nonstopmode -view=none -lualatex -shell-escape GeoEfficiency.jl.tex
│    '`, ProcessExited(12)) [12]
└ @ Documenter.Writers.LaTeXWriter ~/.julia/packages/Documenter/G5Sup/src/Writers/LaTeXWriter.jl:166
```

**Comment by mortenpi** [comment]
I can replicate it, but I don't see why the `pdflatex` build errors. [Here are the LaTeX logs.](https://gist.github.com/mortenpi/bd4f08c2c4f45815ebd2e802ae5f37d4). If you or anyone could figure out why the build errors it would help with narrowing down the problem.

I've attached the LaTeX source files: [geoefficiency.tar.gz](https://github.com/JuliaDocs/DocumenterLaTeX.jl/files/3124571/geoefficiency.tar.gz). It should be possible to just run it with 

```
latexmk -interaction=nonstopmode -view=none -lualatex -shell-escape GeoEfficiency.jl.tex
```

to replicate the problem (assuming you have all the necessary [packages and fonts installed](https://juliadocs.github.io/Documenter.jl/stable/man/other-formats/#Compiling-using-natively-installed-latex-1); on Ubuntu you can just install the same stuff the [Docker image does](https://github.com/JuliaDocs/DocumenterLaTeX.jl/blob/master/docker/Dockerfile)).

**Comment by DrKrar** [comment]
Thanks for the reply, I just check it now.
I am working on windows so it will not that easy to download all.
I am not an expert in Travis if any one can tell me what to do to retrieve the error from Travis build temp it would be nice.
thanks again.
